# Generated by Django 4.1.4 on 2022-12-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0002_remove_userinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='a@a.cc', max_length=254),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='123456', max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='total_score',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
