# Generated by Django 4.1.4 on 2022-12-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0003_userinfo_email_userinfo_loss_userinfo_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
