# Generated by Django 4.1.4 on 2023-01-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0005_alter_userinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
