# Generated by Django 4.1.5 on 2023-01-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0006_alter_userinfo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='username',
        ),
    ]
