# Generated by Django 4.1.5 on 2023-01-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0008_filedown'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fileDown',
        ),
    ]
