# Generated by Django 4.1.5 on 2023-02-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0011_remove_profile_user_profile_email_profile_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
